# fly.toml app configuration file generated for remix-genes-23 on 2023-05-18T02:32:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-genes-23"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[env]
PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
